#!/usr/bin/env bash

atom_packages=(
	'atom-beautify'
	'atom-clock'
	'atom-jest-snippets'
	'atom-runner'
	'autoclose-html'
	'autocomplete-asciidoc'
	'autocomplete-lodash'
	'autocomplete-modules'
	'autocomplete-sql'
	'autocomplete-xml'
	'browser-plus'
	'ctrl-dir-scroll'
	'docblockr'
	'editorconfig'
	'emmet'
	'emmet-jsx-css-modules'
	'file-icons'
	# 'git-plus'
	'goto-definition'
	'highlight-selected'
	'language-asciidoc'
	'language-babel'
	'language-docker'
	# 'language-swift'
	'linter'
	'linter-eslint'
	'linter-ruby'
	'linter-write-good'
	'local-history'
	'lodash-snippets'
	'maximize-panes'
	'minimap'
	'minimap-bookmarks'
	'minimap-cursorline'
	'minimap-find-and-replace'
	'minimap-git-diff'
	'minimap-highlight-selected'
	'minimap-linter'
	'nuclide'
	'one-vibrancy'
	'pigments'
	# 'platformio-ide-terminal'
	'prettier-atom'
	# 'project-manager'
	'project-plus'
	'ruby-block'
	'ruby-test'
	'ruby-test-switcher'
	'simple-drag-drop-text'
	'sort-lines'
	'source-preview'
	'tabs-to-spaces'
	# 'tool-bar'
)

echo -e "\n==> Installing Atom packages..."
for package in ${atom_packages[@]}; do
	apm i $package &> /dev/null
done
